Add support for exporting metrics in the Prometheus format
alphagov/paas-cf-apps-statsd pull request #27
Opened 2018-03-26 09:57 UTC by tuzz

https://trello.com/c/N0D2eNGd/326-edit-paas-metric-exporter-to-make-it-work-with-prometheus

This pull request adds support for exporting metrics to a Prometheus server. The application can be run with the optional `ENABLE_PROMETHEUS` environment variable. If set, the application runs a HTTP handler that serves a `/metrics` endpoint and uses `PrometheusSender` internally to expose metrics to this endpoint.

We did some refactoring as part of this work to allow the `Sender` to be swapped out.

We've added some basic documentation to the readme for our changes, but once our team's project moves from `alpha` we'll likely add some additional set up steps to our public-facing documentation. For example, currently the application does not require a route for statsd as it pushes to a statsd server, whereas for Prometheus it does require a route to be bound to the application in the PaaS space.

2018-04-11 12:34 UTC, philandstuff commented
@dcarley any update on this?

2018-04-11 13:56 UTC, dcarley commented
> @dcarley any update on this?

I'm sorry, I got distracted by firebreak. I'll have a closer look at it this week.

2018-04-13 14:59 UTC, dcarley requested changes
This is good 👍 Thanks for adding Prometheus support and for refactoring the senders to be more modular.

I did find the PR quite hard to review. The entire diff was too large for me to comprehend as a whole. Yet the individual commits were too small to reason about where it was going, particularly because they didn't contain enough information about why a change was being made and often added temporary code that was later refactored out. If you're able to, I think it's worth squashing some of the commits into logical groups before we merge, so that it's easier for other contributors to reason about the history in future.

Could you also run `go fmt ./...` over the branch to standardise code formatting? You might want to configure your editor to do it automatically for you (personally I like [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports)). We should add a CI test to check this in future, but it doesn't have to be done in this PR.

2018-04-13 14:59 UTC, dcarley commented on presenters/path_test.go
> +            Expect(err).To(HaveOccurred())
Can we [match a specific error](https://onsi.github.io/gomega/#matcherrorexpected-interface) here (and the test below it) to ensure that we don't have a false result?

2018-04-13 14:59 UTC, dcarley commented on senders/prometheus_test.go
> +type m []*io_prometheus_client.MetricFamily
The short type name made this code harder for me to follow. Can we use a more descriptive name, or not use a custom type?

2018-04-13 14:59 UTC, dcarley commented on senders/prometheus_test.go
> +            Expect(len(families)).To(Equal(1))
Can this (and the similar tests in the same file) make this assertion before selecting the first item from the slice so that we don't get any panics on test failures?

2018-04-13 14:59 UTC, dcarley commented on app/app.go
> +				// TODO Refactor when we move Send() off the metric
What kind of refactoring did you have in mind? What would cause us to move `Send()` off of `metric`? Will this happen naturally as someone else works on the codebase?

I'm not sure whether this comment is providing much value to future readers of the code.

2018-04-13 14:59 UTC, dcarley commented on manifest.yml
> -  no-route: true
This might cause problems for people that are following the [instructions linked from the README](https://docs.cloud.service.gov.uk/#metrics) because the default route name (based on the app name) will not be unique.

I wonder if we could suggest setting the route on from the CLI if you want to use Prometheus support? Or always using [random-route](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#random-route)?

2018-04-13 14:59 UTC, dcarley commented on metrics/metric_test.go
> +	f.stat = metric.Metric // should this be the presented name?
(whoops: forgot to edit this note to myself)

I'm not sure I understand what this means. Can we resolve the comment now?

2018-04-13 14:59 UTC, dcarley commented on senders/prometheus_test.go
> +    sender := NewPrometheusSender()
I'd prefer this to be setup for each test with `BeforeEach` so that there are no implicit side-effects between test cases.

2018-04-13 14:59 UTC, dcarley commented on README.md
> -export METRIC_WHITELIST="cpu,diskBytes,responseTime.2xx,requests"
We (the PaaS team) should let people know about this potentially breaking change.

We should also start versioning/tagging releases.

2018-04-24 15:10 UTC, philandstuff commented on presenters/path_test.go
> +            Expect(err).To(HaveOccurred())
I'm not sure what exactly you're asking here - do you want us to assert that the error has class `template.ExecError`? How would that look?

2018-04-24 15:12 UTC, philandstuff commented on presenters/path_test.go
> +            Expect(err).To(HaveOccurred())
I had a look for existing patterns of this in the codebase, but couldn't find anything :(

2018-04-24 15:16 UTC, dcarley commented on presenters/path_test.go
> +            Expect(err).To(HaveOccurred())
Matching the error message string would be sufficient (`MatchError` will take an `error` or `string`), e.g.
```go
Expect(err).To(MatchError("some error message"))
```

2018-04-30 14:45 UTC, dcarley commented on README.md
> -export METRIC_WHITELIST="cpu,diskBytes,responseTime.2xx,requests"
@chrisfarms and I have been talking about this. We're going to look at tagging the current release and advising people to deploy from tags rather than master.

We wondered whether moving the response codes to the templating was necessary though. Aside from being a breaking change, it feels like a more complex use of the templating feature than it was originally intended for. Is it possible to keep the existing interface?

2018-04-30 14:47 UTC, dcarley commented
Thanks for the squashing/rebasing!

Would you also be able to squash the last commit ("Fixed according to review by dcarley") into the relevant commit(s)? After we've merged this it won't give much information to somebody looking at the commit history.

2018-05-03 15:54 UTC, philandstuff commented on README.md
> -export METRIC_WHITELIST="cpu,diskBytes,responseTime.2xx,requests"
I don't think there's a short answer to this question, but I'll try:

This is to do with the difference between the statsd/graphite hierarchical naming style and the prometheus/influxdb/opentsdb label-based naming style, and about how template parameters become labels.

With graphite, it doesn't matter much if `{{.Metric}}` expands to `responseTime.2xx` or if you have separate variables for `{{.Metric}}` and `{{.StatusCode}}` (or `{{.Metadata.statusRange}}` in this case), because either way you can construct a metric called `myorg.myspace.myapp.responseTime.2xx`.  There is extra complexity if the metric name and status code range is split up, but it doesn't change what's possible.

With Prometheus, we care about what goes into the metric name and what goes into the labels.  Ideally, we'd have something like `http_server_response_time{org="myorg",space="myspace",app="myapp",code_range="2xx"}`.  We can't do this (without horrible hacks) if the metric name is `responseTime.2xx`, and the response code range is separate.

While it might be possible to have metrics like `http_server_responseTime.2xx{org="myorg",space="myspace",app="myapp"}`, this would be surprising to users because it would not be in the standard expected form, and would be difficult to write queries around (say, if you wanted to average response times across all status code ranges).

I think the issue may be that we've had to change the underlying data structures in order to expose the metric name and the status code range as separate values to prometheus.  As an unintended consequence, the `text_template` processor in `presenters/path.go` has changed its interface, which allowed raw access to the underlying `Metric` data structure.  I think it might be possible to add a shim in `presenters/path.go` which recreates the original `{{.Metric}}` value of `responseTime.2xx` by translating a `Metric` to a new `MetricView` of some sort which recreates the original interface.  How would that sound?

2018-05-03 17:17 UTC, philandstuff commented on README.md
> -export METRIC_WHITELIST="cpu,diskBytes,responseTime.2xx,requests"
I've added 385d4093660f141a5540bb31e969b51de2ccc194 as a proof of concept which reverts to the previous templating behaviour for the statsd sender.  It works by separating concerns between the {Counter,Gauge,PrecisionTiming}Metric model objects and a new MetricView structure specifically for templating.  Would this approach suit you?  If so, I can squash it in (I've left it separate while we agree an approach).

Note that this *doesn't* revert to the previous whitelisting behaviour -- your comment mentioned templating, but it was in the file context of whitelisting.  Can you clarify if it's the breaking changes in whitelisting, templating, or both that you care about?

I think it will be harder to do a similar change for whitelisting, because I think the internal domain model of Metrics does have to change if we are to accomodate prometheus in the way I mentioned above, and the whitelisting code operates directly on the Metric model.  I don't see that we can do a similar MetricView trick.

2018-05-04 14:03 UTC, philandstuff commented
@chrisfarms finally squashed everything down and repushed.

2018-05-04 16:01 UTC, dcarley approved these changes

2018-05-04 16:02 UTC, merged

2018-05-04 16:02 UTC, chrisfarms commented
Thanks for working through the changes @philandstuff 👍